# Generated by Django 3.0.6 on 2020-05-11 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strasse', models.CharField(max_length=512, verbose_name='Straße')),
                ('plz', models.CharField(max_length=5, verbose_name='PLZ')),
                ('ort', models.CharField(max_length=512, verbose_name='Ort')),
                ('entfernung', models.IntegerField(help_text='Entfernung in km', verbose_name='Entfernung (km)')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
                'ordering': ['plz'],
            },
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vorname', models.CharField(max_length=200)),
                ('nachname', models.CharField(max_length=200)),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fahrtenliste_main.Adresse')),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'ordering': ['nachname', 'vorname'],
            },
        ),
        migrations.CreateModel(
            name='Fahrt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fahrt_nr', models.IntegerField(blank=True, null=True)),
                ('datum', models.DateField()),
                ('entfernung', models.IntegerField(blank=True, help_text='Entferung in km. Zusätzlich gespeichert, da sich die Entfernung z.B. eigenem bei Umzug ändern kann.', null=True)),
                ('betrag', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('steuer', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('konto', models.CharField(blank=True, max_length=100, null=True)),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('adresse', models.ForeignKey(blank=True, help_text='Die Ziel Adresse. Zusätzlich gespeichert, da der Kunde umziehen kann.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fahrtenliste_main.Adresse')),
                ('kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fahrtenliste_main.Kunde')),
            ],
            options={
                'verbose_name': 'Fahrt',
                'verbose_name_plural': 'Fahrten',
                'ordering': ['-datum', '-id', 'kommentar'],
            },
        ),
    ]
