# Generated by Django 3.0.6 on 2020-05-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrtenliste_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunde',
            name='anrede',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='vorname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
