# Generated by Django 3.0.6 on 2020-05-17 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahrtenliste_main', '0002_kunde_anrede'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einstellung',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('wert_date', models.DateField(blank=True, null=True)),
                ('wert_char', models.CharField(blank=True, max_length=255, null=True)),
                ('wert_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Einstellung',
                'verbose_name_plural': 'Einstellungen',
            },
        ),
        migrations.AlterField(
            model_name='fahrt',
            name='adresse',
            field=models.ForeignKey(blank=True, help_text='Die Ziel Adresse, wird bei Neueingabe der Fahrt automatisch gefüllt. Zusätzlich gespeichert, da der Kunde umziehen kann.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fahrtenliste_main.Adresse'),
        ),
        migrations.AlterField(
            model_name='fahrt',
            name='entfernung',
            field=models.IntegerField(blank=True, help_text='Entferung in km, wird bei Neueingabe der Fahrt automatisch gefüllt. Zusätzlich gespeichert, da sich die Entfernung z.B. eigenem bei Umzug ändern kann.', null=True, verbose_name='Entfernung (km)'),
        ),
    ]
