# Generated by Django 3.0.6 on 2020-05-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrtenliste_main', '0003_einstellung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adresse',
            options={'ordering': ['plz'], 'verbose_name': 'Adresse', 'verbose_name_plural': ' Adressen'},
        ),
        migrations.AlterModelOptions(
            name='einstellung',
            options={'ordering': ['name'], 'verbose_name': 'Einstellung', 'verbose_name_plural': 'Einstellungen'},
        ),
        migrations.AlterModelOptions(
            name='fahrt',
            options={'ordering': ['-datum', '-id', 'kommentar'], 'verbose_name': 'Fahrt', 'verbose_name_plural': '   Fahrten'},
        ),
        migrations.AlterModelOptions(
            name='kunde',
            options={'ordering': ['nachname', 'vorname'], 'verbose_name': 'Kunde', 'verbose_name_plural': '  Kunden'},
        ),
    ]
