# Generated by Django 3.0.6 on 2020-06-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrtenliste_main', '0004_model_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='strasse',
            field=models.CharField(max_length=512, verbose_name='Straße und Hausnummer'),
        ),
        migrations.AlterModelTable(
            name='adresse',
            table='adresse',
        ),
        migrations.AlterModelTable(
            name='einstellung',
            table='einstellung',
        ),
        migrations.AlterModelTable(
            name='fahrt',
            table='fahrt',
        ),
        migrations.AlterModelTable(
            name='kunde',
            table='kunde',
        ),
    ]
