# Generated by Django 3.0.6 on 2020-06-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrtenliste_main', '0006_einstellung_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunde',
            name='adresse_historisch',
            field=models.TextField(blank=True, help_text='Die ursprüngliche Adresse, falls die Adresse gelöscht wird.', null=True, verbose_name='Adresse Historie'),
        ),
    ]
