# Generated by Django 3.0.6 on 2020-06-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fahrtenliste_main', '0008_fahrt_kunde_adresse_historisch'),
    ]

    operations = [
        migrations.AddField(
            model_name='einstellung',
            name='beschreibung',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='einstellung',
            name='wert_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL("insert into einstellung"
                          " (name, wert_int, beschreibung)"
                          " values"
                          " ('min_fahrt_nr', 1, 'Die kleinste Fahrt Nr. bei automatischer Vergabe');",
                          reverse_sql=""),
    ]
